language: ruby
rvm:
  - 1.9.3
env:
  - RAILS_ENV=travis
before_script:
  - mysql -e 'create database statusbot_test;'
script:
  - bundle exec rake db:migrate
  - CODECLIMATE_REPO_TOKEN=00007462f169c0875debb825d2835df9ff46ce933b63ffaae16f017e205db091 bundle exec rake spec
deploy:
  api_key:
    secure: U3Mg1zldY1RNAdRJ26a0V3acwiuZSwPn4AuGhXwFnKKEua5Xvqu1H6gQsOGvxJMxmb7b9jYlY9K+sZ9YCs10HQ2Y7E5oagB9pedl4fNzb772G7ayXa1qb6cUX2DUOQP/zoyJu5Z9TaPcwHXC0A6WAoZayGoXPPeScGdImvuSF2g=
