development:
  adapter: mysql2
  encoding: utf8
  database: statusbot
  pool: 5
  username: statusbot
  password: password
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: statusbot_test
  pool: 5
  username: statusbot_test
  password: password
  socket: /tmp/mysql.sock

travis:
  adapter: mysql2
  database: statusbot_test
  username: travis
  encoding: utf8
